[package]
name = "discord-bot-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
rusqlite = "0.31.0"
anyhow = "1.0.86"
regex = "1.10.5"
serde = "1.0.204"
